# Generated by Django 5.2.6 on 2025-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLMTS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='photo_confirmation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='signature_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
