# Generated by Django 5.2.6 on 2025-10-27 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLMTS_app', '0004_authtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidtag',
            old_name='scanned_at',
            new_name='verified_at',
        ),
        migrations.RemoveField(
            model_name='rfidtag',
            name='scanned_by',
        ),
        migrations.RemoveField(
            model_name='rfidtag',
            name='task',
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='item_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tags', to='SLMTS_app.user'),
        ),
    ]
