# Generated by Django 5.2.6 on 2025-10-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLMTS_app', '0005_rename_scanned_at_rfidtag_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfidtag',
            options={},
        ),
        migrations.CreateModel(
            name='IndividualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_items', to='SLMTS_app.orderitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='individual_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tag', to='SLMTS_app.individualitem'),
        ),
    ]
